"""empty message

Revision ID: 091a3a8c66d5
Revises: c0288a18cae5
Create Date: 2020-05-10 18:27:00.333137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091a3a8c66d5'
down_revision = 'c0288a18cae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_access_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('referrer_url', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('query_parma', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=32), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_error_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('referrer_url', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('query_parma', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_error_log')
    op.drop_table('app_access_log')
    # ### end Alembic commands ###
