"""empty message

Revision ID: b9f7d4b7abae
Revises: b41840c2b601
Create Date: 2020-04-09 00:42:29.255679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9f7d4b7abae'
down_revision = 'b41840c2b601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'login_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('user', 'login_pwd',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('user', 'login_salt',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('user', 'nikename',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user', 'sex',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'update_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user', 'sex',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user', 'nikename',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'login_salt',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'login_pwd',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'login_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'avatar',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
