"""empty message

Revision ID: c0288a18cae5
Revises: cea2a4bf969e
Create Date: 2020-04-25 11:17:45.432228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0288a18cae5'
down_revision = 'cea2a4bf969e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
