"""empty message

Revision ID: cea2a4bf969e
Revises: d932f396d35b
Create Date: 2020-04-11 16:52:12.205601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cea2a4bf969e'
down_revision = 'd932f396d35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=64), nullable=False))
    op.drop_column('user', 'nikename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nikename', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
